### ISSUE TITLE
Update Pagar.me brand assets

### ISSUE THREAD

**Issue by mccraveiro** [pagarme/brand#1]
The brand has changed. However this repo is not up to date.

**Comment by derekstavis** [comment]
Yep! I'm in touch with the brand team and waiting for them to release the brand book so we can update this repository with proper material.

**Comment by MarcoWorms** [comment]
https://avatars1.githubusercontent.com/u/3846050?v=4&s=200

just for future reference

**Comment by flaviolee** [comment]
Brand updated! <3

**Comment by hmaesta** [comment]
Here we go _again._ This repo is not up to date.
